apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-debug
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: "ubuntu:16.04"
    volumeMounts:
      - name: nfs
        mountPath: "/mnt/weblogic-pool"
    command: ["/bin/sleep"]
    args: ["infinity"]

  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs