apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  # minikube mount ~/workspace/mount-dir/:/mnt/pv
  hostPath:
    path: "/mnt/pv"